### PR TITLE
Adding implementation and tests for Rule D4 for FABS submissions

### PR DESCRIPTION
**Pull request by nmonga91**
Adding implementation and tests for Rule D4 for FABS submissions

### CODE REVIEW

**Comment by kkuratsu** [comment]
Do we need to have a test case for null?
A/C: * This is a required field for all submissions and cannot be blank.

**Comment by nmonga91** [comment]
The requirement check happens at an earlier stage and therefore does not need to happen at the SQL level

**Comment by nmonga91** [comment]
We should be using `COALESCE` though. I will add that.

**Comment by kkuratsu** [comment]
Why the test for nulll in d4_2 and d4_3 passes the test? Should it give an error if the action_date is null?

**Comment by nmonga91** [comment]
d4_2 and d4_3 should pass for Null because they operate assuming they operate on an actual date. If it's not a date, there's no point in running them. We can have @kaitlin confirm that that functionality/assumption is acceptable though.

**Comment by kaitlin** [comment]
Makes sense to me. We shouldn't run this validation if the value is null.

**Pull request merged**
