### PR TITLE
DEV-1158: Update FABS parent DUNS

### PR DESCRIPTION
**Pull request by dpb-bah**
**High level description:**
Includes script to backfill the ultimate parent name/duns for FABS data using the historic parent duns table. 

**Technical Release Notes:**
* Includes function to get the name of a DUNS directly via the SAM service
* Adding the latest monthly file to represent the DUNS data from the latest year
* Includes two SQL statements, one to update the FABS where the action date + DUNS match the historical parent DUNS table, the other to use the earliest action date + DUNS when there isn't a match

**Link to JIRA Ticket:**
[DEV-1158](https://federal-spending-transparency.atlassian.net/browse/DEV-1158)

**The following are ALL required for the PR to be merged:**
- [x] Backend review completed
- Unit & integration tests updated with relevant test cases (N/A)
- Frontend impact assessment completed (N/A)
- [x] Performance Review
- [x] Data Review

### CODE REVIEW

**Comment by michaeldhess** [comment]
[run tests]

**Comment by dpb-bah** [comment]
### Performance Review
Ran on Broker Dev (note: some records are still null as the historic parent duns at the time didn't have 2018 data)
```
+ docker run -i --rm=true --env env=dev fedora/data-act-db-build-dev-1158-update-fabs-parent-duns /bin/sh -c 'export PYTHONPATH='\''/data-act/backend'\''; python3 /data-act/backend/dataactcore/scripts/update_fabs_parent_duns.py '
2018-06-28 09:56:23,133 INFO:__main__:Gathering historical parent duns names via SAM service
2018-06-28 09:56:24,596 INFO:__main__:Updating historical parent duns names
2018-06-28 09:56:25,190 WARNING:dataactcore.utils.fileE:{'message': 'Message from SAM API: [Basic Error: No records found that match the criteria.]', 'message_type': 'CoreWarning'}
...
2018-06-28 10:15:14,815 WARNING:dataactcore.utils.fileE:{'message': 'Message from SAM API: [Basic Error: No records found that match the criteria.]', 'message_type': 'CoreWarning'}
2018-06-28 10:15:17,888 INFO:__main__:Updated historical Parent DUNS names through SAM service, took 1134.755122423172 seconds
2018-06-28 10:15:18,374 INFO:__main__:Updating historical Parent DUNS names using internal data
2018-06-28 10:15:18,378 INFO:dataactcore.utils.parentDuns:Updating missing parent names
2018-06-28 10:15:21,777 INFO:dataactcore.utils.parentDuns:Processing row 1 - 10000 with missing parent duns name
2018-06-28 10:15:22,545 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7678053379058838 s
2018-06-28 10:15:22,546 INFO:dataactcore.utils.parentDuns:Processing row 10001 - 20000 with missing parent duns name
2018-06-28 10:15:23,261 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7152988910675049 s
2018-06-28 10:15:23,261 INFO:dataactcore.utils.parentDuns:Processing row 20001 - 30000 with missing parent duns name
2018-06-28 10:15:23,965 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7033050060272217 s
2018-06-28 10:15:23,965 INFO:dataactcore.utils.parentDuns:Processing row 30001 - 40000 with missing parent duns name
2018-06-28 10:15:24,719 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7539763450622559 s
2018-06-28 10:15:24,720 INFO:dataactcore.utils.parentDuns:Processing row 40001 - 50000 with missing parent duns name
2018-06-28 10:15:25,467 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7470202445983887 s
2018-06-28 10:15:25,467 INFO:dataactcore.utils.parentDuns:Processing row 50001 - 60000 with missing parent duns name
2018-06-28 10:15:26,242 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7746710777282715 s
2018-06-28 10:15:26,242 INFO:dataactcore.utils.parentDuns:Processing row 60001 - 70000 with missing parent duns name
2018-06-28 10:15:26,983 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.740447998046875 s
2018-06-28 10:15:26,983 INFO:dataactcore.utils.parentDuns:Processing row 70001 - 80000 with missing parent duns name
2018-06-28 10:15:27,718 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.734748363494873 s
2018-06-28 10:15:27,718 INFO:dataactcore.utils.parentDuns:Processing row 80001 - 90000 with missing parent duns name
2018-06-28 10:15:28,458 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7396242618560791 s
2018-06-28 10:15:28,458 INFO:dataactcore.utils.parentDuns:Processing row 90001 - 100000 with missing parent duns name
2018-06-28 10:15:29,255 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7970519065856934 s
2018-06-28 10:15:29,256 INFO:dataactcore.utils.parentDuns:Processing row 100001 - 110000 with missing parent duns name
2018-06-28 10:15:30,022 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7666704654693604 s
2018-06-28 10:15:30,023 INFO:dataactcore.utils.parentDuns:Processing row 110001 - 118379 with missing parent duns name
2018-06-28 10:15:30,770 INFO:dataactcore.utils.parentDuns:Updated 0 rows in HistoricParentDUNS with the parent name in 0.7469978332519531 s
2018-06-28 10:15:30,790 INFO:__main__:Updated historical Parent DUNS names using internal data, took 12.415991067886353 seconds
2018-06-28 10:15:30,790 INFO:__main__:Updating FABS with action dates matching the years within the parent duns
2018-06-28 10:15:31,342 INFO:__main__:Updated FABS with action dates matching the years within the parent duns, took 0.5516273975372314 seconds
2018-06-28 10:15:31,342 INFO:__main__:Updating FABS with action dates not matching the parent duns, using the earliest match
2018-06-28 10:15:41,469 INFO:__main__:Updated FABS with action dates not matching the parent duns, using the earliest match, took 10.126476287841797 seconds
2018-06-28 10:15:41,472 INFO:__main__:Historical parent DUNS FABS updates complete.
Finished: SUCCESS
```

**Comment by sharb** [comment]
Can one of the admins verify this patch?

**Comment by sharb** [comment]
Can one of the admins verify this patch?

**Pull request merged**
