### PR TITLE
Update container name in Install guide

### PR DESCRIPTION
**Pull request by BrianZito**
In my experimentation, the backend container is just called dataact-broker, not dataact-broker-backed

### CODE REVIEW

**Comment by kopite1986** [comment]
Hi I am really keen to contribute to projects on GitHub but even though I clone the repository to my environment, I don't know which .py file to apply the changes to. can someone help please? Sorry to jump on this. How do I know if I want to work on an open issue where to get the source code to apply the changes to?

**Comment by BrianZito** [comment]
Hi, If you open an issue in this repo with plenty of details I can point people your way.

**Comment by dpb-bah** [comment]
Oh weird. When I follow the guide, I have the following docker containers:
```
> docker ps
... dataact-broker-frontend
... dataact-broker-backend
... dataact-broker-validator
... dataact-broker-db
```

**Comment by BrianZito** [comment]
I was using an outdated version of the containers. Values in readme match docker-compose.

**Pull request closed without merging**
