### PR TITLE
Doc updates for MAX.gov Login URL changes

### PR DESCRIPTION
**Pull request by rrenomeron**
**High level description:**
Updates to API Submission docs to reflect recent changes to MAX.gov Login.

**Technical details:**
Update URL in APISubmissionGuide.md and update copy of "Using Digital Certificates for MAX Authentication.pdf" from canonical source at https://community.max.gov/x/vYdjVg.

Since this is a doc-only update, I didn't change any test cases (a cursory search of the repo didn't find anything referencing "piv.max.gov").

**Link to JIRA Ticket:**
https://maxjira.max.gov/browse/CAS-1761 (internal to MAX.gov)

The following are ALL required for the PR to be merged:
- [x] Frontend impact assessment completed
- [x] Documentation Updated

### CODE REVIEW

**Comment by dpb-bah** [comment]
Hi @rrenomeron , is `https://login.max.gov` going to be modified as well or is that still the same?

**Comment by rrenomeron** [comment]
I'm assuming you're asking about the endpoints that DataBroker uses to validate the tickets posted on your /v1/login endpoint (e.g. https://login.max.gov/cas/serviceValidate).  If that's a valid assumption, then the answer is "no, https://login.max.gov is not going to be modified".

(Apologies for the excess wordiness, just want to make sure I'm being clear.)

**Comment by dpb-bah** [comment]
Thanks @rrenomeron . If you can merge from dev, I'll merge it soon.

**Comment by rrenomeron** [comment]
Merge done; waiting on Travis to do its thing.

**Pull request merged**
