### PR TITLE
Hotfix sys submission tagging

### PR DESCRIPTION
**Pull request by nmonga91**
"SYS" agency is now an option for submissions if the current, logged in user is part of the "SYS" agency

### CODE REVIEW

**Comment by jworcestBAH** [comment]
I'm wondering if it would be better to do the append outside this function, just because this function looks like something that would potentially be reused if we want to list agencies for anything else.  If we don't do that, could we put a docstring on the listAgencies function warning about this exception so we don't accidentally misuse it?  Alternately, a checkForSys flag that defaults to false would perhaps make this clearer.

**Comment by nmonga91** [comment]
So right now it's also being used for registration, but without an x-session-id the `isLogin` check returns false and skips it. I wouldn't mind moving it out but `getAllAgencies` should be the function being reused vs this one that's specifically for a route. I can also add the docstring

**Comment by jworcestBAH** [comment]
Okay let's just add the docstring then, and have that mention that this adds SYS for those users

**Comment by nmonga91** [comment]
@jworcestBAH docstring has been added

**Pull request merged**
