### PR TITLE
-Allowing domain and tas values to be loaded from s3 bucket when use_…

### PR DESCRIPTION
**Pull request by klrBAH**
…aws is set to true.

-Renaming in-repo domain and tas files to "example_" since they will be updated in the s3 going forward.

### CODE REVIEW

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by cmc333333** [comment]
Rockin @klrBAH -- would you mind thinking through any README updates we'll need? We can follow up after this sprint.

**Pull request merged**
