### PR TITLE
Change TAS file format

### PR DESCRIPTION
**Pull request by cmc333333**
We're getting our TAS files from a different source now, which has a slightly
different set of columns. Modify the import script to accommodate and replace
the CSVs included in the app. The logic is simplified as our data source is
now more accurate (not including duplicate rows, for example).

This is a first step towards replacing the `tas` field in our models with the new `ACCT_NUM`-based approach.

### CODE REVIEW

**Comment by jworcestBAH** [comment]
Have you tested loading the new all_tas_betc.csv file and making sure the tas_lookup table gets populated?  This file is not used during the testing, so we should test that the new file can be loaded correctly before making this change.

**Comment by cmc333333** [comment]
@jworcestBAH thanks for pushing back! It does indeed load the data and the integration test data has been updated to use the new headers. I hadn't tried running through a validation, however, which is failing. Investigating now.

**Comment by cmc333333** [comment]
Updated to account for strings of spaces and added some tests; ready for re-review

**Comment by jworcestBAH** [comment]
Looks like my last question was about code that got deleted, so merging now

**Pull request merged**
