### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by cmc333333**
~~@bsweger's GlobalDB commit was lost in the shuffle.~~ Also adds basic, configurable logging

### CODE REVIEW

**Comment by bsweger** [comment]
@cmc333333 @jworcestBAH Sorry for the confusion around this, but that branch I made based on CM's db tweaks contains things intended for the current sprint weren't meant to deploy right now.

**Comment by cmc333333** [comment]
Understood, @bsweger -- force-pushed to remove that changeset

**Comment by bsweger** [comment]
@cmc333333 Thanks for setting this up. At your suggestion, I had swapped out some print statements with the logger in the domain values load script. Is the intent here to give a global means of using the Python logger instead of print statements? How would this work in conjunction with what we're already logging to logstash?

**Comment by cmc333333** [comment]
I'm going to close this in favor of DB-1110; I think the `CloudLogger` is _so_ close to being a logging handler. Let's combine that with this code, soon.

**Pull request closed without merging**
