### PR TITLE
Refactor database connection manager

### PR DESCRIPTION
**Pull request by cmc333333**
One step towards centralizing database connection management. This uses `flask.g` where available to resolve some threading issues while also pulling database connection info into a separate class. Ideally, we'll remove all of the database information from `BaseInterface` and instead pass it along explicitly or grab it from the thread-safe context, `flask.g`.

### CODE REVIEW

**Comment by jworcestBAH** [comment]
Has this been tested in sandbox to see if it resolves issues with d-file threads?

**Comment by cmc333333** [comment]
It has not (I don't know how), but it does resolve a local threading issue (the local server spins up several threads). It still uses a static variable for non-flask work, so I don't think it'd resolve a connection issue in the celery worker. That said, it'd be pretty straight forward to wrap the worker function in a `app_context` to get the benefits here.

**Comment by klrBAH** [comment]
[run tests]

**Comment by klrBAH** [comment]
[run tests]

**Comment by cmc333333** [comment]
This became part of #248

**Pull request closed without merging**
